/** Backend [backend/src/common/menu-visibility.ts] ile aynı anahtarlar */
export const MENU_KEYS = [
  'dashboard',
  'inbox',
  'contacts',
  'leads',
  'products',
  'quotes',
  'orders',
  'accounting',
  'tasks',
  'calendar',
  'admin',
  'reports',
  'integrations',
  'settings',
  'support',
  'ecommerce',
  'superadmin',
] as const;

export const MENU_KEY_LABELS: Record<string, string> = {
  dashboard: 'Gösterge Paneli',
  inbox: 'Mesajlar',
  contacts: 'Kişiler',
  leads: 'Potansiyel Müşteriler',
  products: 'Ürünler',
  quotes: 'Teklifler',
  orders: 'Siparişler',
  accounting: 'Muhasebe',
  tasks: 'Görevler',
  calendar: 'Takvim',
  admin: 'Yönetim',
  reports: 'Raporlar',
  integrations: 'Entegrasyonlar',
  settings: 'Ayarlar',
  support: 'Destek',
  ecommerce: 'E-Ticaret',
  superadmin: 'SaaS Panel',
};
